### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by faustinoaq** [obskyr/hamtaro-in-pieces#1]
Hi @obskyr, very nice project, I tried it and I got some syntax errors:

```
make --no-print-directory -C tools/
make[1]: Nothing to be done for 'all'.
rgbasm -i source/ -h -E -o build/gbc_only_screen.o source/gbc_only_screen.asm
ERROR: source/gbc_only_screen.asm(63):
        Invalid macro argument
ERROR: source/gbc_only_screen.asm(63):
        syntax error
error: Assembly aborted in pass 1 (2 errors)!
make: *** [Makefile:27: build/gbc_only_screen.o] Error 1
```

**Comment by obskyr** [comment]
Ah, yes, that's a line with an escaped newline - a feature that was only introduced in RGBDS 0.3.6, which came out just the other week. I put together the readme in a bit of a rush, so it seems I forgot to mention RGBDS at *all*! If you upgrade to 0.3.6, it *should* work.
